[package]
name = "NPSlicer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "NPSlicer"
path = "src/main.rs"

[dependencies]
npslicer_core = { path = "../core"}

iced = { version = "0.14.0", features = ["debug", "image", "advanced", "wgpu", "tokio"] }
wgpu = "27.0"
image = { version = "0.25", default-features = false }
bytemuck = { version = "1.0", features = ["derive"] }
glam = { version = "0.25", features = ["bytemuck"] }
rand = "0.8.5"


rfd = "0.15.3"
tokio = { version = "1.45.1", features = ["fs"] }
stl_io = "0.8.2"
